language: csharp
os:
  - linux
dist: trusty
osx_image: xcode8.3
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono:
  - 5.2.0
dotnet: 2.0.0
script:
  - ./build.sh --target "Travis" --platform "NetCoreOnly" --configuration "Release"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/98f653320ef2b7506c05
    on_success: change
    on_failure: always
    on_start: never
