os: Visual Studio 2015
platform:
- Any CPU
configuration:
- Release
environment:
  NUGET_API_KEY:
    secure: ADD_SECURE_NUGET_API_KEY_HERE
  NUGET_API_URL: https://www.nuget.org/api/v2/package
  MYGET_API_KEY:
    secure: XOgD5bJUKNOS2kDDgb+affS4pDcslxALh+xvvnr1Koy0PjXlhILsBdNhxRe0KcNm
  MYGET_API_URL: https://www.myget.org/F/avalonia-ci/api/v2
install:
  - if not exist gtk-sharp-2.12.26.msi appveyor DownloadFile http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi
  - msiexec /i gtk-sharp-2.12.26.msi /qn /norestart
  - cmd: set PATH=%programfiles(x86)%\GtkSharp\2.12\bin\;%PATH%
before_build:
- git submodule update --init
build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Platform "$env:platform" -Configuration "$env:configuration"
after_build:
- .\packages\JetBrains.dotMemoryUnit.2.1.20150828.125449\tools\dotMemoryUnit.exe -targetExecutable="%xunit20%\xunit.console.x86.exe" -returnTargetExitCode  --"tests\Avalonia.LeakTests\bin\Release\Avalonia.LeakTests.dll"
test: off
artifacts:
  - path: artifacts\nuget\*.nupkg
cache:
  - gtk-sharp-2.12.26.msi
